# Generated by Django 5.1.15 on 2026-04-08 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendances",
                to="classrooms.classroom",
                verbose_name="Aula",
            ),
        ),
    ]
