# Generated by Django 5.1.15 on 2026-04-08 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dni",
                    models.CharField(max_length=8, unique=True, verbose_name="DNI"),
                ),
                ("nombres", models.CharField(max_length=150)),
                ("apellidos", models.CharField(max_length=150)),
                ("especialidad", models.CharField(blank=True, max_length=200)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("fecha_ingreso", models.DateField(verbose_name="Fecha de ingreso")),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profesor",
                "verbose_name_plural": "Profesores",
                "ordering": ["apellidos", "nombres"],
            },
        ),
        migrations.CreateModel(
            name="TeacherContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TIEMPO_COMPLETO", "Tiempo completo"),
                            ("MEDIO_TIEMPO", "Medio tiempo"),
                            ("POR_HORAS", "Por horas"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de contrato",
                    ),
                ),
                (
                    "sueldo",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sueldo"
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Dejar vacío para contrato indefinido",
                        null=True,
                        verbose_name="Fecha de fin",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="TeacherPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mes",
                    ),
                ),
                ("anio", models.IntegerField(verbose_name="Año")),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                ("fecha_pago", models.DateField(verbose_name="Fecha de pago")),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("TRANSFERENCIA", "Transferencia"),
                            ("EFECTIVO", "Efectivo"),
                            ("DEPOSITO", "Depósito"),
                        ],
                        max_length=15,
                        verbose_name="Método de pago",
                    ),
                ),
                (
                    "comprobante",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Comprobante"
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-anio", "-mes"],
            },
        ),
    ]
