# Generated by Django 5.2.14 on 2026-05-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherpayment',
            options={'ordering': ['-anio', '-mes'], 'verbose_name': 'Sueldo pagado', 'verbose_name_plural': 'Sueldos'},
        ),
    ]
