# Generated by Django 5.1.15 on 2026-04-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destinatario",
                    models.EmailField(max_length=254, verbose_name="Destinatario"),
                ),
                ("asunto", models.CharField(max_length=300, verbose_name="Asunto")),
                ("contenido", models.TextField(verbose_name="Contenido")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RECORDATORIO_PAGO", "Recordatorio de pago"),
                            ("COMUNICACION", "Comunicación"),
                            ("ALERTA_ASISTENCIA", "Alerta de asistencia"),
                            ("BIENVENIDA", "Bienvenida"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("enviado", models.BooleanField(default=False, verbose_name="Enviado")),
                ("error", models.TextField(blank=True, verbose_name="Error")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log de email",
                "verbose_name_plural": "Logs de email",
                "ordering": ["-created_at"],
            },
        ),
    ]
