# Generated by Django 5.1.15 on 2026-04-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(unique=True, verbose_name="Fecha")),
                (
                    "total_alumnos",
                    models.IntegerField(default=0, verbose_name="Total alumnos"),
                ),
                (
                    "total_profesores",
                    models.IntegerField(default=0, verbose_name="Total profesores"),
                ),
                (
                    "alumnos_por_nivel",
                    models.JSONField(default=dict, verbose_name="Alumnos por nivel"),
                ),
                (
                    "ingresos_mes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Ingresos del mes",
                    ),
                ),
                (
                    "egresos_mes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Egresos del mes",
                    ),
                ),
                (
                    "balance_mes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Balance del mes",
                    ),
                ),
                (
                    "porcentaje_morosidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="% Morosidad",
                    ),
                ),
                (
                    "porcentaje_asistencia",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="% Asistencia",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Métrica del dashboard",
                "verbose_name_plural": "Métricas del dashboard",
                "ordering": ["-fecha"],
            },
        ),
    ]
