# Generated by Django 5.1.15 on 2026-04-20 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_session_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='UUID de la sesión actualmente activa. Al hacer login se regenera.', verbose_name='ID de sesión activa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN_JARDIN', 'Admin Jardín'), ('DIRECTOR', 'Director(a)'), ('SECRETARIA', 'Secretaria'), ('PROFESOR', 'Profesor(a)')], default='ADMIN_JARDIN', max_length=20, verbose_name='Rol'),
        ),
    ]
