# Generated by Django 5.2.14 on 2026-05-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('ADMIN_JARDIN', 'Admin Jardín'), ('TEACHER', 'Profesor')], default='ADMIN_JARDIN', max_length=20, verbose_name='Rol'),
        ),
    ]
