# Generated by Django 5.1.15 on 2026-04-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "nivel_edad",
                    models.IntegerField(
                        choices=[
                            (2, "2 años"),
                            (3, "3 años"),
                            (4, "4 años"),
                            (5, "5 años"),
                        ],
                        verbose_name="Nivel de edad",
                    ),
                ),
                (
                    "capacidad",
                    models.PositiveIntegerField(default=25, verbose_name="Capacidad"),
                ),
                ("anio_escolar", models.IntegerField(verbose_name="Año escolar")),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "ordering": ["anio_escolar", "nivel_edad", "nombre"],
            },
        ),
    ]
