# Generated by Django 5.1.15 on 2026-04-08 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classrooms", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="profesor_auxiliar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aulas_auxiliar",
                to="teachers.teacher",
                verbose_name="Profesor auxiliar",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="profesor_titular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aulas_titular",
                to="teachers.teacher",
                verbose_name="Profesor titular",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together={("nombre", "anio_escolar")},
        ),
    ]
