# Generated by Django 5.1.15 on 2026-04-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='activo',
        ),
    ]
