# Generated by Django 5.1.15 on 2026-04-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_remove_classroom_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['nivel_edad', 'nombre'], 'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='anio_escolar',
        ),
    ]
