# Generated by Django 5.2.14 on 2026-05-23 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_alter_classroom_options_and_more'),
        ('teachers', '0005_alter_teacherpayment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='profesor_auxiliar',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'AUXILIAR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_auxiliar', to='teachers.teacher', verbose_name='Profesor auxiliar'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='profesor_titular',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'TITULAR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_titular', to='teachers.teacher', verbose_name='Profesor titular'),
        ),
    ]
