# Generated by Django 5.1.15 on 2026-04-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='estado',
        ),
    ]
