# Generated by Django 5.1.15 on 2026-04-30 23:32

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Plan COREM', max_length=80)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=Decimal('120.00'), help_text='Precio mensual por jardín en soles', max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plan / Configuración',
                'ordering': ('-activo', '-creado_at'),
            },
        ),
        migrations.CreateModel(
            name='PlatformCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=160)),
                ('categoria', models.CharField(choices=[('HOSTING_BACK', 'Hosting backend (Railway)'), ('HOSTING_FRONT', 'Hosting frontend (Vercel)'), ('DOMINIO', 'Dominio'), ('EMAIL', 'Email / SMTP'), ('STORAGE', 'Almacenamiento'), ('OTROS', 'Otros')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('recurrente', models.BooleanField(default=False, help_text='Marca si es un gasto mensual recurrente')),
                ('notas', models.TextField(blank=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Si el gasto aplica a un jardín específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Gasto operativo',
                'verbose_name_plural': 'Gastos operativos',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_acordado', models.DecimalField(decimal_places=2, help_text='Precio negociado para este jardín. Default = precio del plan.', max_digits=8)),
                ('fecha_alta', models.DateField(default=datetime.date.today)),
                ('trial_hasta', models.DateField(blank=True, help_text='Hasta esta fecha el jardín no se cobra. Default: alta + 1 mes.', null=True)),
                ('estado', models.CharField(choices=[('TRIAL', 'En periodo de prueba'), ('ACTIVA', 'Activa'), ('MOROSA', 'En mora (3-7 días)'), ('BLOQUEADA', 'Bloqueada por impago'), ('CANCELADA', 'Cancelada')], default='TRIAL', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='platform.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='tenants.tenant', verbose_name='Jardín')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ('-fecha_alta',),
            },
        ),
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('CONDONADA', 'Condonada')], default='PENDIENTE', max_length=10)),
                ('fecha_emision', models.DateField(default=datetime.date.today)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, help_text='Yape, Plin, Transferencia, etc.', max_length=20)),
                ('referencia', models.CharField(blank=True, help_text='Nº de operación', max_length=80)),
                ('notas', models.TextField(blank=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant', verbose_name='Jardín')),
            ],
            options={
                'verbose_name': 'Cobro mensual',
                'verbose_name_plural': 'Cobros mensuales',
                'ordering': ('-anio', '-mes', 'tenant__nombre'),
                'unique_together': {('tenant', 'mes', 'anio')},
            },
        ),
    ]
