# Generated by Django 5.2.13 on 2026-05-04 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('es_promocional', '-activo', '-creado_at'), 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AddField(
            model_name='plan',
            name='descripcion',
            field=models.CharField(blank=True, help_text="Descripción visible (ej: '2x1 mes de aniversario', 'Verano 2026', etc.)", max_length=240),
        ),
        migrations.AddField(
            model_name='plan',
            name='es_promocional',
            field=models.BooleanField(default=False, help_text='Marca si es un plan promocional o de campaña (no el plan principal)', verbose_name='Promocional / campaña'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='dia_cobro',
            field=models.PositiveSmallIntegerField(default=1, help_text='Día del mes en que se emite el cobro (1-28).', verbose_name='Día de cobro'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='estado',
            field=models.CharField(choices=[('TRIAL', 'Prueba'), ('ACTIVA', 'Activa'), ('MOROSA', 'Mora'), ('BLOQUEADA', 'Bloqueada'), ('CANCELADA', 'Cancelada')], default='TRIAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='fecha_alta',
            field=models.DateField(default=datetime.date.today, help_text='Fecha en que el jardín fue dado de alta en COREM (inicio del periodo de prueba).', verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='trial_hasta',
            field=models.DateField(blank=True, help_text='Hasta esta fecha el jardín no se cobra. Default: alta + 30 días.', null=True, verbose_name='Trial hasta'),
        ),
    ]
