# Generated by Django 5.2.14 on 2026-05-28 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_plan_tiers'),
        ('tenants', '0003_alter_tenant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TIER_MISMATCH', 'Tier desactualizado')], max_length=30)),
                ('nivel', models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('contexto', models.JSONField(blank=True, default=dict, help_text='Datos estructurados de la alerta. Para TIER_MISMATCH: {plan_actual, tier_correcto, alumnos_activos}.')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('resuelta_at', models.DateTimeField(blank=True, null=True)),
                ('notas_resolucion', models.TextField(blank=True)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='tenants.tenant', verbose_name='Jardín')),
            ],
            options={
                'verbose_name': 'Alerta del SaaS',
                'verbose_name_plural': 'Alertas del SaaS',
                'ordering': ('-creado_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('resuelta_at__isnull', True)), fields=('tenant', 'tipo'), name='unique_open_alert_per_tenant_type')],
            },
        ),
    ]
