# Generated by Django 5.1.15 on 2026-04-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicMigration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio_origen", models.IntegerField(verbose_name="Año origen")),
                ("anio_destino", models.IntegerField(verbose_name="Año destino")),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de ejecución"
                    ),
                ),
                (
                    "total_migrados",
                    models.IntegerField(default=0, verbose_name="Total migrados"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEW", "Preview"),
                            ("EJECUTADO", "Ejecutado"),
                            ("ROLLBACK", "Rollback"),
                        ],
                        default="PREVIEW",
                        max_length=10,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Migración académica",
                "verbose_name_plural": "Migraciones académicas",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="MigrationDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(max_length=20, verbose_name="Estado anterior"),
                ),
                (
                    "estado_nuevo",
                    models.CharField(max_length=20, verbose_name="Estado nuevo"),
                ),
            ],
            options={
                "verbose_name": "Detalle de migración",
                "verbose_name_plural": "Detalles de migración",
            },
        ),
    ]
