# Generated by Django 5.1.15 on 2026-04-08 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classrooms", "0002_initial"),
        ("migrations_academic", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="academicmigration",
            name="ejecutado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academic_migrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ejecutado por",
            ),
        ),
        migrations.AddField(
            model_name="migrationdetail",
            name="aula_destino",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="migration_details_destino",
                to="classrooms.classroom",
                verbose_name="Aula destino",
            ),
        ),
        migrations.AddField(
            model_name="migrationdetail",
            name="aula_origen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="migration_details_origen",
                to="classrooms.classroom",
                verbose_name="Aula origen",
            ),
        ),
        migrations.AddField(
            model_name="migrationdetail",
            name="migration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="migrations_academic.academicmigration",
                verbose_name="Migración",
            ),
        ),
        migrations.AddField(
            model_name="migrationdetail",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="migration_details",
                to="students.student",
                verbose_name="Alumno",
            ),
        ),
    ]
