# Generated by Django 5.2.15 on 2026-07-22 22:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_student_ficha_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DATOS_PERSONALES', 'Tratamiento de datos personales del menor'), ('DATOS_SALUD', 'Tratamiento de datos de salud (ficha médica)'), ('IMAGEN', 'Uso de imagen (fotografías y video)'), ('COMUNICACIONES', 'Envío de comunicaciones al apoderado')], max_length=20, verbose_name='Tipo')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(help_text='Texto completo de la cláusula/política que el apoderado acepta.', verbose_name='Contenido')),
                ('obligatorio', models.BooleanField(default=True, help_text='Si el jardín no puede prestar el servicio sin este consentimiento.', verbose_name='Obligatorio')),
                ('vigente_desde', models.DateField(default=django.utils.timezone.now, verbose_name='Vigente desde')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento de consentimiento',
                'verbose_name_plural': 'Documentos de consentimiento',
                'ordering': ['tipo', '-version'],
                'unique_together': {('tipo', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otorgado', models.BooleanField(default=True, verbose_name='Otorgado')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de la decisión')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='students.guardian', verbose_name='Apoderado que consiente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='students.student', verbose_name='Alumno')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='consents.consentdocument', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['student', 'documento'], name='consents_co_student_520b7e_idx'), models.Index(fields=['documento', 'otorgado'], name='consents_co_documen_dbec30_idx')],
            },
        ),
    ]
