# Generated by Django 5.2.14 on 2026-05-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='plan',
        ),
    ]
