# Generated by Django 5.2.14 on 2026-05-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_remove_tenant_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['nombre'], 'verbose_name': 'Jardín', 'verbose_name_plural': 'Jardines'},
        ),
    ]
