# Generated by Django 5.1.15 on 2026-04-08 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dni",
                    models.CharField(max_length=8, unique=True, verbose_name="DNI"),
                ),
                ("nombres", models.CharField(max_length=150)),
                ("apellidos", models.CharField(max_length=150)),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de nacimiento"),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        max_length=1,
                        verbose_name="Género",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="students/fotos/"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("RETIRADO", "Retirado"),
                            ("EGRESADO", "Egresado"),
                            ("ELIMINADO", "Eliminado"),
                        ],
                        default="ACTIVO",
                        max_length=10,
                    ),
                ),
                ("fecha_ingreso", models.DateField(verbose_name="Fecha de ingreso")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="classrooms.classroom",
                        verbose_name="Aula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alumno",
                "verbose_name_plural": "Alumnos",
                "ordering": ["apellidos", "nombres"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_sangre",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de sangre",
                    ),
                ),
                ("alergias", models.TextField(blank=True, verbose_name="Alergias")),
                (
                    "seguro",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Seguro médico"
                    ),
                ),
                (
                    "hospital_referencia",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Hospital de referencia",
                    ),
                ),
                (
                    "contacto_emergencia_nombre",
                    models.CharField(
                        max_length=200, verbose_name="Contacto de emergencia (nombre)"
                    ),
                ),
                (
                    "contacto_emergencia_telefono",
                    models.CharField(
                        max_length=20, verbose_name="Contacto de emergencia (teléfono)"
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ficha_medica",
                        to="students.student",
                        verbose_name="Alumno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha médica",
                "verbose_name_plural": "Fichas médicas",
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=8, verbose_name="DNI")),
                ("nombres", models.CharField(max_length=150)),
                ("apellidos", models.CharField(max_length=150)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "parentesco",
                    models.CharField(
                        choices=[
                            ("PADRE", "Padre"),
                            ("MADRE", "Madre"),
                            ("TUTOR", "Tutor"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "es_principal",
                    models.BooleanField(
                        default=False, verbose_name="Es apoderado principal"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apoderados",
                        to="students.student",
                        verbose_name="Alumno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apoderado",
                "verbose_name_plural": "Apoderados",
                "unique_together": {("student", "dni")},
            },
        ),
    ]
