# Generated by Django 5.1.15 on 2026-04-17 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de ingreso'),
        ),
    ]
