# Generated by Django 5.1.15 on 2026-04-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ficha_matricula',
            field=models.FileField(blank=True, help_text='Documento oficial de matrícula firmado por el apoderado', null=True, upload_to='students/fichas/', verbose_name='Ficha de matrícula (PDF)'),
        ),
    ]
