# Generated by Django 5.1.15 on 2026-04-08 20:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio_escolar", models.IntegerField(verbose_name="Año escolar")),
                (
                    "monto_mensual",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto mensual"
                    ),
                ),
                (
                    "dia_vencimiento",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Dia del mes para vencimiento",
                        verbose_name="Día de vencimiento",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_fees",
                        to="students.student",
                        verbose_name="Alumno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pensión mensual",
                "verbose_name_plural": "Pensiones mensuales",
                "ordering": ["-anio_escolar", "student__apellidos"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mes",
                    ),
                ),
                ("anio", models.IntegerField(verbose_name="Año")),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PAGADO", "Pagado"),
                            ("VENCIDO", "Vencido"),
                            ("EXONERADO", "Exonerado"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(verbose_name="Fecha de vencimiento"),
                ),
                (
                    "fecha_pago",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de pago"
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("YAPE", "Yape"),
                            ("PLIN", "Plin"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=15,
                        verbose_name="Método de pago",
                    ),
                ),
                (
                    "comprobante",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Comprobante"
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="Código QR",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "monthly_fee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="payments.monthlyfee",
                        verbose_name="Pensión mensual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-anio", "-mes", "student__apellidos"],
            },
        ),
    ]
