# Generated by Django 5.1.15 on 2026-04-08 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("contenido", models.TextField(verbose_name="Contenido")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("GENERAL", "General"), ("POR_AULA", "Por aula")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de envío"
                    ),
                ),
                ("enviado", models.BooleanField(default=False, verbose_name="Enviado")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo requerido si el tipo es POR_AULA",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communications",
                        to="classrooms.classroom",
                        verbose_name="Aula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comunicación",
                "verbose_name_plural": "Comunicaciones",
                "ordering": ["-created_at"],
            },
        ),
    ]
