# Generated by Django 5.1.15 on 2026-04-08 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CashCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("EGRESO", "Egreso")],
                        max_length=7,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=False,
                        help_text="Categorías generadas automáticamente por el sistema",
                        verbose_name="Es categoría de sistema",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Categoría de caja",
                "verbose_name_plural": "Categorías de caja",
                "ordering": ["tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.IntegerField(verbose_name="Mes")),
                ("anio", models.IntegerField(verbose_name="Año")),
                (
                    "total_ingresos",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total ingresos"
                    ),
                ),
                (
                    "total_egresos",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total egresos"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Balance"
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "fecha_cierre",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de cierre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cierre mensual",
                "verbose_name_plural": "Cierres mensuales",
                "ordering": ["-anio", "-mes"],
            },
        ),
        migrations.CreateModel(
            name="CashTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=300, verbose_name="Descripción"),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("EGRESO", "Egreso")],
                        max_length=7,
                        verbose_name="Tipo",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="cashflow.cashcategory",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción",
                "verbose_name_plural": "Transacciones",
                "ordering": ["-fecha", "-created_at"],
            },
        ),
    ]
