# Generated by Django 5.1.15 on 2026-04-08 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cashflow", "0001_initial"),
        ("payments", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cashtransaction",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="cashtransaction",
            name="referencia_pago",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_transactions",
                to="payments.payment",
                verbose_name="Pago vinculado",
            ),
        ),
        migrations.AddField(
            model_name="cashtransaction",
            name="referencia_teacher_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_transactions",
                to="teachers.teacherpayment",
                verbose_name="Pago de profesor vinculado",
            ),
        ),
        migrations.AddField(
            model_name="monthlyclosure",
            name="cerrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="monthly_closures",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cerrado por",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthlyclosure",
            unique_together={("mes", "anio")},
        ),
    ]
